In [63]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten

X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[44,3,3,4],[4,33,13,64],[74,63,73,94],[14,3,33,41]]).astype('float32')

model = Sequential()
model.add(Dense(32, input_dim=2))
model.add(Activation("relu"))
model.add(Dense(32))
model.add(Activation("relu"))
model.add(Dense(4))
model.compile(loss="mean_absolute_error", optimizer="adam", metrics = ['accuracy'])

history = model.fit(X, y, epochs=10000, verbose=0)
print(model.predict(X))


[[ 43.99945831   2.99562001   2.99183607   4.00132942]
 [  4.00979948  33.0275116   13.00525761  64.02523041]
 [ 73.94109344  62.99327469  72.99807739  93.99253845]
 [ 13.99605274   3.02497959  33.01667404  41.02381516]]


In [62]:
test = np.array([[10.1,10.1],[333.1,31.1],[113.1,40.1],[14.1,11.1]]).astype('float32')
print(model.predict(test))

[[  58.67420959   47.59828568   51.10503387   73.62433624]
 [   5.17925644    7.86434174   88.98207092  113.52604675]
 [ 275.37261963  280.62106323  332.46847534  436.20141602]
 [  68.36287689   63.29825974   70.63109589   96.68739319]]
