In [5]:
import numpy as np

X = np.array([[0.1,0.1,0.1],[0.9,0.9,0.1],[0.2,0.2,0.1],[0.8,0.8,0.1],[0.1,0.05,0.1],[0.9,0.95,0.1]])
y = np.array([[0,1,0,1,0,1]]).T 
syn1 = 2*np.random.random((3,1)) - 1
print(syn1)

[[-0.1229198 ]
 [ 0.74113875]
 [ 0.02492771]]


In [7]:
for j in range(1000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn1)))) 
    l1_delta = (y - l1)*(l1*(1-l1))  
    syn1 += X.T.dot(l1_delta)
    print(syn1)

[[0.04523495]
 [0.91969631]
 [0.01158944]]
[[ 0.15460785]
 [ 1.03839417]
 [-0.00907894]]
[[ 0.23002308]
 [ 1.12252801]
 [-0.03399349]]
[[ 0.28459801]
 [ 1.18545679]
 [-0.06152093]]
[[ 0.3254742 ]
 [ 1.23444977]
 [-0.09076668]]
[[ 0.35684058]
 [ 1.27376878]
 [-0.12120253]]
[[ 0.38132573]
 [ 1.30608706]
 [-0.15249481]]
[[ 0.40067199]
 [ 1.33317592]
 [-0.18442099]]
[[ 0.41608589]
 [ 1.35626155]
 [-0.21682604]]
[[ 0.42843278]
 [ 1.37622316]
 [-0.24959818]]
[[ 0.43835112]
 [ 1.39370927]
 [-0.28265451]]
[[ 0.44632306]
 [ 1.40920952]
 [-0.31593212]]
[[ 0.45271965]
 [ 1.42310063]
 [-0.34938237]]
[[ 0.45783104]
 [ 1.43567713]
 [-0.3829671 ]]
[[ 0.46188703]
 [ 1.44717226]
 [-0.41665592]]
[[ 0.46507171]
 [ 1.45777283]
 [-0.45042442]]
[[ 0.46753387]
 [ 1.4676298 ]
 [-0.48425277]]
[[ 0.46939472]
 [ 1.47686613]
 [-0.51812477]]
[[ 0.47075365]
 [ 1.48558262]
 [-0.55202708]]
[[ 0.47169258]
 [ 1.49386238]
 [-0.58594866]]
[[ 0.47227942]
 [ 1.50177424]
 [-0.61988033]]
[[ 0.47257059]
 [ 1.50937544]
 [-0.65

In [4]:
print l1

[[ 0.19966139]
 [ 0.92491595]
 [ 0.28885045]
 [ 0.88325856]
 [ 0.16915001]
 [ 0.93786788]]
